<?xml version="1.0"?>

<!--  

Gazebo Hummingbird Definition File
Author: James Jackson

-->

<robot name="hummingbird" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="namespace" value="$(arg mav_name)" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://fcu_sim/meshes/hummingbird.dae" />
  <xacro:property name="mass" value="0.5755" /> <!-- [kg] -->
  <xacro:property name="body_width" value="0.1" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.12" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.009" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.17" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.01" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.1" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg m/s^2] -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0025" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.0025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="838" /> <!-- [rad/s] -->
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />
  <xacro:property name="body_inertia">
    <inertia ixx="0.182" ixy="0.0" ixz="0.0" iyy="0.179" iyz="0.0" izz="0.3258" />
  </xacro:property>
  <xacro:property name="rotor_inertia">
    <xacro:box_inertia x="${radius_rotor}" y="0.015" z="0.003" mass="${mass_rotor*rotor_velocity_slowdown_sim}" />
  </xacro:property>


  <!-- *********************** GAZEBO ROBOT DEFINITION ******************* -->
  <link name="${namespace}/base_link">
    <inertial>
      <mass value="${mass}" />  <!-- [kg] -->
      <origin xyz="0 0 0" />
      <xacro:insert_block name="body_inertia" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 .785" />
      <geometry>
        <xacro:if value="${use_mesh_file}">
          <mesh filename="${mesh_file}" scale="1 1 1" />
        </xacro:if>
        <xacro:unless value="${use_mesh_file}">
          <box size="${body_width} ${body_width} ${body_height}"/>
        </xacro:unless>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${body_width} ${body_width} ${body_height}" />
      </geometry>
    </collision>
  </link>


  <!-- ************************* ROTOR DYNAMICS ********************** -->
  <gazebo>
    <plugin filename="libfcu_sim_multirotor_base_plugin.so" name="multirotor_base_plugin">
      <robotNamespace>${namespace}</robotNamespace>
      <linkName>${namespace}/base_link</linkName>
      <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
    </plugin>i
  </gazebo>


  <!-- **************** ROTORS ***************** -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/rotor.xacro"/>
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${.707*arm_length} -${.707*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${.707*arm_length} ${.707*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="back_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Black"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${.707*arm_length} ${.707*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="back_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Black"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${.707*arm_length} -${.707*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>


  <!-- ***************** SENSORS ******************* -->
  <!-- Mount an ADIS16448 IMU. -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/imu.xacro"/>
  <xacro:IMU_ADIS16448 
    namespace="${namespace}" 
    parent_link="${namespace}/base_link"
    imu_topic="/imu/data" />

  <!-- Enable Ground Truth -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/odometry_sensor.xacro"/>
  <xacro:ground_truth namespace="${namespace}" parent_link="${namespace}/base_link" />

</robot>
